import type { Metadata } from "next";
import { Roboto ,AR_One_Sans} from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import AuthProvider from "@/store/AuthContext";
import AdminAppProvider from "@/store/AdminContext";

const arOneSans = AR_One_Sans({
  variable: "--font-ar-one-sans",
  subsets: ["latin"],
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${arOneSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <AdminAppProvider>
            <ToastContainer />
            {children}
          </AdminAppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
